feat: adaptive hero
GuildOfDevelopers/guild-of-developers-frontend pull request #14
Opened 2022-09-23 21:36 UTC by achemakin

2022-09-25 08:45 UTC, StelsP requested changes

2022-09-25 08:45 UTC, StelsP commented on src/components/Hero/style.tsx
> +  max-width: 280px;
`max-width: 288px;`

2022-09-25 08:45 UTC, StelsP commented on src/components/Hero/style.tsx
> +    gap: 26px;
тут gap вроде ничего не делает

2022-09-25 08:45 UTC, StelsP commented on src/components/Hero/style.tsx
>  export const MembersItem = styled.li`
тут на мобилке `gap: 6px`;

2022-09-25 08:45 UTC, StelsP commented on src/components/Hero/style.tsx
> +
добавь на этой строчке   
```
@media (max-width: 320px) {
    padding-inline: 10px;
  }
```
чтобы учесть ширину galaxy fold, которая 280px

2022-09-25 08:45 UTC, StelsP commented on src/lib/styled/global.tsx
> +    min-width: 320px;
это плохая практика, удали

2022-09-25 19:00 UTC, achemakin commented on src/components/Hero/style.tsx
> +    gap: 26px;
Здесь gap нужен, когда блок сжимается, чтобы Li не слипались.

2022-09-26 20:27 UTC, StelsP approved these changes

2022-09-27 07:20 UTC, merged