Feature/mobile header
GuildOfDevelopers/guild-of-developers-frontend pull request #16
Opened 2022-09-25 12:31 UTC by Maden51

Добавил адаптив для Хэдера. Работа над анимацией ещё в процессе.

2022-09-25 13:30 UTC, StelsP requested changes
1) меню в открытом состояниее сдвигает все вниз, а должно перекрывать
дизайн:
![image](https://user-images.githubusercontent.com/67414792/192145073-64969e1c-a4f3-467b-a730-e1a356b1502c.png)
у нас:
![image](https://user-images.githubusercontent.com/67414792/192145088-f883df61-7bec-442c-a41e-9ac8dbb8daa0.png)

2) закинь все, что относится к header в папку header
![image](https://user-images.githubusercontent.com/67414792/192145964-543e9bbe-61f8-44d8-b5d0-1bcf487950c3.png)
может это не лучшее решение, но пока давай сделаем так
3) раз сделал `MobileHeader` отдельным копонентом, то можешь сделать тогда и `DesktopHeader`
и в самом header будет уже что-то такое
![image](https://user-images.githubusercontent.com/67414792/192146085-b36ada08-ae08-4f16-938b-69425770bea5.png)

2022-09-25 13:30 UTC, stelsp commented on src/layout/MobileHeader/index.tsx
> +              {/* <NavBarLink to="/login"> */}
поудаляй пока закомменченные ссылки, что не засоряло, по мере готовности страниц будем убирать пропс и менять адрес ссылки лучше

2022-09-25 13:30 UTC, stelsp commented on src/layout/MobileHeader/index.tsx
> +              {/* <NavBarLink to="/login"> */}
и там в консоле ошибка (это мой косяк) 
![image](https://user-images.githubusercontent.com/67414792/192144066-3836f1ee-e32e-43b9-adb3-7f34bd771db5.png)
переименуй пропс просто в `wip` пожалуйста

2022-09-25 13:30 UTC, StelsP commented on src/lib/styled/global.tsx
> +    --color-black-menu: #333333;
ошибка дизайна, это удали
используй  `--color-black: #000000;` в меню

2022-09-25 13:30 UTC, StelsP commented on src/components/MenuToggle/index.tsx
> +            closed: { d: 'M 2 2.5 L 20 2.5', stroke: '#333333' },
ошибка дизайна, используй  `--color-black: #000000;`

2022-09-25 13:30 UTC, StelsP commented on src/components/MenuToggle/index.tsx
> +            closed: { d: 'M 2 2.5 L 20 2.5', stroke: '#333333' },
ну везде =)

2022-09-25 13:30 UTC, StelsP commented on src/layout/MobileHeader/style.tsx
> +            content: 'WIP';
переименуй во что то более понятное для юзера, на твой выбор

2022-09-25 13:30 UTC, StelsP commented on src/layout/MobileHeader/index.tsx
> +import Button from '../../components/NavBarButton';
переименуй тут в `NavBarButton` и в самом компоненте тоже

2022-09-25 13:30 UTC, StelsP commented on src/services/hooks.ts
> +export function useMediaQuery(query: string): boolean {
вынеси хук в отдельный файл в этой же папке `useMediaQueryHook`

2022-09-25 13:30 UTC, StelsP commented on src/layout/MobileHeader/style.tsx
> +  padding: 22px 16px;
оставь тут только `padding-block: 20px` (22px 100% в дизайне ошибка) а паддинги горизонтальные ты можешь получить за счет `<Container />` так же как и в десктоп версии, для этого конейтнер просто перенеси выше (см скрин) (12  и 46 строчка на нем)
![image](https://user-images.githubusercontent.com/67414792/192145833-1fef2c51-b3bf-4963-bee7-1434ef7ddd7a.png)

2022-09-26 05:47 UTC, 1PopovAleksey commented on src/components/MenuToggle/index.tsx
> +            closed: { d: 'M 2 2.5 L 20 2.5', stroke: '#333333' },
А может будем теперь ещё строже проверят дизайн? Чтобы такого не было:

> ну везде =)

@StelsP

2022-09-27 07:27 UTC, StelsP approved these changes

2022-09-27 07:27 UTC, merged