Feature/form registration
GuildOfDevelopers/guild-of-developers-frontend pull request #30
Opened 2022-10-28 09:36 UTC by achemakin

Добавил:
- страницу регистрации Pages/registration, 
- форму регистрации components/RegistrationForm,
- выпадающий список вынес в отдельный модуль components/DropdownList,
Внес изменения в components/Filter:
- избавился от всех className,
- реализовал передачу props в styled-components, 
- реализовал стилизацию компонентов @headlessui/react с использованием styled-components

2022-10-28 12:47 UTC, StelsP requested changes
и посмотри ошибки в консоле 
![image](https://user-images.githubusercontent.com/67414792/198590277-22c31866-2eac-4fdd-983b-d1deefdbd155.png)

2022-10-28 12:47 UTC, StelsP commented on src/components/RegistrationForm/index.tsx
> +                  <svg
сделай svg отдельными компонентами в этой же папке

2022-10-28 12:47 UTC, StelsP commented on src/components/RegistrationForm/index.tsx
> +                  <svg
тут тоже

2022-10-29 18:12 UTC, achemakin commented on src/components/RegistrationForm/index.tsx
> +                  <svg
Сделал

2022-10-29 18:12 UTC, achemakin commented on src/components/RegistrationForm/index.tsx
> +                  <svg
Сделал

2022-10-30 00:07 UTC, StelsP approved these changes

2022-10-30 00:07 UTC, merged